#! /bin/bash

#set -x
#set -o

gpg_cmd="/usr/bin/gpg2"
db_path="$HOME/.pass.gpg"
delimiter='/'
view_pass=0


declare -a passwords
username=''
password=''

function clipboard {
  local password="$1"

  # Copy to clipboard with xsel
  if type xsel >/dev/null; then
    echo "$password" | xsel -b -i
  else
    echo "No clipboard implemented"
  fi
}

function import_gpg_db {
  local i=0

  if [ -f "$db_path" ]; then
    for pass in $($gpg_cmd < "$db_path" 2>/dev/null); do
      passwords[$i]=$pass
      ((i++))
    done
  else
    echo "Can not find databse"
    echo "Creating empty database in $db_path"
    echo > "$db_path"
  fi

}

function export_gpg_db {
  local tmp

  echo "${passwords[@]}"
  for (( i=0; i<${#passwords[@]}; i++ )); do
    tmp="${passwords[i]}\n"
    passwords[i]="$tmp"
  done

  echo -e "${passwords[@]}" | $gpg_cmd -c > $db_path 

}

function add_pass {
  local service="$1"

  passwords+=(${service}${delimiter}${username}${delimiter}${password})
  export_gpg_db
  
}

function remove_pass {
  local service="$1"
  
  for pass_nr in {0..#passwords}; do
    if [[ $passwords[$pass_nr] =~ ^${service} ]]; then
     echo lol 
    fi
  done
}

function return_pass {
   local service="$1"
   local i=0

   for pass in "${passwords[@]}"; do
     if [[ $pass =~ ^${service}${delimiter}(.+)${delimiter}(.+)$ ]]; then
       if [[ $view_pass -eq 1 ]]; then
        echo "User: ${BASH_REMATCH[1]}"
        echo "Password: ${BASH_REMATCH[2]}"
      else
        echo "User: ${BASH_REMATCH[1]} Copied to CLIPBOARD"
        clipboard "${BASH_REMATCH[2]}"
      fi
     fi
   done
}

function _usage {
  cat <<EOF
Usage: $0 [options] service
      add                          add the password to databse
      del                          deletes the password from the database
      -v| --view                   view the password in cleartext
      -u| --user                   change or add username for service
      -p| --pass                   change or add password for service
      -h| --help                   prints usage menu
EOF
}



##### MAIN #####
action="lookup"
if [[ $# -eq 0 ]]; then
  _usage
  exit 1
fi

while [[ $# -ge 1 ]]; do

  case "$1" in
    add)
      action="add"
      ;;
    del)
      action="del"
      ;;
    -v|--view)
      view_pass=1
      ;;
    -u|--user)
      username="$2"
      ;;
    -p|--pass)
      password="$2"
      ;;
    -h|--help)
      _usage
      exit 0
      ;;
  esac
  shift
done

import_gpg_db
service="$BASH_ARGV"
case $action in
  lookup)
    return_pass "$service"
    ;;
  add)
    add_pass "$service"
    ;;
  del)
    remove_pass "$service"
    ;;
  *)
    echo "Invalid option"
esac
